#!/bin/bash
# -*- coding: utf-8 -*-

echo "安裝 Stellarium"

if [ $DISTRO_ID = "Ubuntu" ]; then
#    apt-get -f --force-yes install ttf-droid
    export STELLARIUM_FONT="DroidSansFallback.ttf";
    export STELLARIUM_FONT_DIR="ttf-droid";
elif [ $DISTRO_ID = "Debian" ]; then
#    apt-get -f --force-yes install ttf-wqy-zenhei
    export STELLARIUM_FONT="wqy-zenhei.ttc";
    export STELLARIUM_FONT_DIR="wqy";
fi

export STELLARIUM_DATA='/usr/share/stellarium/data';

echo "Add chinese language support."

# ln font
ln -s -f /usr/share/fonts/truetype/${STELLARIUM_FONT_DIR}/${STELLARIUM_FONT} ${STELLARIUM_DATA}/${STELLARIUM_FONT}

# config.ini & default_config.ini sed options
export CONFIG_SED="-r -e 's/^(app|sky)_locale([\t ]*)=([\t ]*).+$/\1_locale\2=\3zh_TW/g'
-e 's/^base_font_name([\t ]*)=([\t ]*).+$/base_font_name\1=\2"${STELLARIUM_FONT}"/g'
-e 's/^location([\t ]*)=([\t ]*).+$/location\1=\2中央大學鹿林天文台, Taiwan/g' ";

# fontmap.dat
sed -i -r -e "s/^zh_(HK|TW).+$/zh_\1\t"${STELLARIUM_FONT}"\t1.2\t"${STELLARIUM_FONT}"\t1.2/g" \
$STELLARIUM_DATA/fontmap.dat

# user_locations.txt
echo -e '中央大學鹿林天文台\t嘉義縣/南投縣\ttw\t0\t0,1\t23.47N\t120.88E\t2862' | \
tee $STELLARIUM_DATA/user_locations.txt > /dev/null

# default_config.ini
eval sed -i $CONFIG_SED $STELLARIUM_DATA/default_config.ini

# config.ini (user, don't sudo)
# don't do anything unless file exists
# -- stellarium will copy default_config.ini at start up.

#Get all user
USERS_DIR=$(cat /etc/passwd | grep bash | cut -d ":" -f 6)

for u in $USERS_DIR
do
    [ -e ${u}.stellarium/config.ini ] \
        && eval sed -i $CONFIG_SED ${u}.stellarium/config.ini
done
