#!/bin/bash
case $PLAT_NAME in
        "i386")
        ./download-install Google_Chrome "http://dl.google.com/dl/linux/direct/google-chrome-beta_current_i386.deb"
        ;;
        "x86_64")
        ./download-install Google_Chrome "http://dl.google.com/dl/linux/direct/google-chrome-beta_current_amd64.deb"
        ;;
        *)
        echo "Sorry, Lazyscripts not support $PLAT_NAME"
        ;;
esac
