#!/bin/bash

wget http://emesene.org/trac/raw-attachment/wiki/Plugins/LastSaid.py

if [ ! -d ${REAL_HOME}/.config/emesene1.0 ]; then
    mkdir -p ${REAL_HOME}/.config/emesene1.0
fi

mv LastSaid.py ${REAL_HOME}/.config/emesene1.0/

